### ISSUE TITLE
lcd problem

### ISSUE THREAD

**Issue by sinanhalici** [fire1/ArduinoMid#5]
is there any image on the LCD at idle standby or is it necessary to print a button?

**Comment by fire1** [comment]
There no standby mode in this project. When you turn of the engine BC is complacently torn off in order to save energy from car battery (in long term). The only way to turn it on is to turn the ignition key back to contact position.

**Comment by sinanhalici** [comment]
Does the display appear on the screen without connect the 32-pin connector?
thanks a lot

**Comment by fire1** [comment]
22pin connector ...? (not 32)
No, fist you need to adjust contrast based to back light. You need to display something to do that.
If you change voltage supply, this need to be re-done again.

**Comment by sinanhalici** [comment]
I have connected 2x16 lcd to arduino mega correctly without Mid bord, but there was nothing on the lcd.

**Comment by fire1** [comment]
In MID.h you will find
`#define SCREEN 24064 // Glcd 240x64`
`//#define SCREEN 162 // lcd 16x2`

comment `#define SCREEN 24064` and uncomment `SCREEN 162`
16x2 LCD type is not used for a long time and may not work well as 240x64

**Comment by sinanhalici** [comment]
I know those code.
I connect LCD to arduino mega correctly and connect arduino mega to computer without ArduinoMidboard, but LCD doesn't show me anything.
Should i connect  32 pins connector and turn on contact after connect  22 pins LCD connector?

**Comment by fire1** [comment]
Can you make clear test with simple display of "hello world" by using same pin connection described in MID.h for screen 162?
For ground connection use analogWrite(<pin>,0); and for 5v use analogWrite(<pin>,255); where is needed 
Place those settings in void setup ()....

Basically this LCD was never used in current version. 

You must wait several days to make a single test from my side :/

**Comment by sinanhalici** [comment]
![img_20171219_193718](https://user-images.githubusercontent.com/33650840/34205661-446125fe-e594-11e7-8975-feeece514e6f.jpg)
Can I connect the LCD on the arduino mid board as I show it with the red lines in the picture on the arduino mid board, or should I make a mixed connection?
For example 1 to 10, 2 to 8 ...

**Comment by fire1** [comment]
This is by default...   LCD pin 1 goes to Arduino Mega 2560 pin 24  / LCD pin 2 to 25

but way you soldered a double sided male row from the wrong side ?
Thous male rows needs to be at the bottom side... to be connected to  Arduino Mega 2560

![p_20171128_201026](https://user-images.githubusercontent.com/1549876/34210104-59ff1ac0-e59d-11e7-8442-2c2f4ec0af05.jpg)

 You will need a two potentiometers for contrast (negative voltage) and back-light to calibrate LCD between connector and cable.


Find me on Facebook Messenger for feedback

**Comment by fire1** [comment]
Can we close this issue?

**Comment by sinanhalici** [comment]
No
Can you wait for finished my circuit?

**Comment by sinanhalici** [comment]
![25498321_1595493650499021_1583701695781226875_n](https://user-images.githubusercontent.com/33650840/34295407-46b871aa-e71e-11e7-87e1-a5b431124791.jpg)
As you can see, the LCD has a male header. I am worried that the LCD will not fit directly on the Arduino.mid board.

**Comment by fire1** [comment]
directly No, with cable Yes 
You will need around  1.5m with 22 pins if you will place it on my recommended place

**Comment by sinanhalici** [comment]
Can you tell me how to connect with cables? I need to know from arduino mid board to lcd.

**Comment by sinanhalici** [comment]
![25855877_1598005380247848_613796546_o](https://user-images.githubusercontent.com/33650840/34319054-dc6d63c6-e7e7-11e7-8ea5-9fcff4a38c92.jpg)
I connected the LCD, there is a blue light on the LCD screen, but there is no image or text. Do I need to connect the 32 pin connector to get the image on screen and do I need to connect arduino.mid board   + 14 volts?

**Comment by fire1** [comment]
Like i was saying several times .... You need  two potentiometers to calibrate contrast.
Check wiring of 240x64:
https://easyeda.com/fire1.a.zaprianov/MID_LCD_240x64-eee21a1e00ac4a4da848eed4253e9cf7

LCD will run only with usb power. 
Place those trimmers closes to ArduinoMid board in order to have acces to them when some changes are made . 
When you place Arduino in car also need to be re-calibrated the contrast.

**Comment by sinanhalici** [comment]
Thanks for your help, but i mean can i see something on the lcd without connecting 32 pins connector? 
I did calibrate, but there is nothing on the lcd. There is only lcd light when i connect usb cable.

**Comment by fire1** [comment]
Yes, without 32pin connector  will show everything only data will be zeroed (junk) ... Also without a board will display ... 

Try rearrange pins for display from MID.h or try other sketch only for testing is display OK

**Comment by fire1** [comment]
Since you have back light... Contrast is missing
To verify this by lowering the value of SCREEN_DEF_LIGHT

**Comment by sinanhalici** [comment]
Can you take a video how to connect and conrast lcd?

**Comment by fire1** [comment]
Impossible... Already installed into car, but you can check this video
https://youtu.be/l0ADfGnYSZ8
There are same just pin number are different
Do you have any lines appearing over the display at beginning, when powering On?

**Comment by fire1** [comment]
I forgot to mention... When adjust the contrast... Rotate backlight and contrast potentiometers at some random point letters will start to appears.
 You must adjust very carefully.
At maximum contrast full screens needs to be bright, do you have such a point? Check negative voltage is OK....

**Comment by sinanhalici** [comment]
actually, we can't understand each other from here.
I don't have any problem to contrast 16x2 LCD. My problem is about 240x64 lcd's connecting and contrast.
in your Picture below the link, how can i give -12v?
I check with multimeter to 20. and pin, but there is no -12 V?
Should i connect different voltage suply for -12V for 20. pin?

https://easyeda.com/fire1.a.zaprianov/MID_LCD_240x64-eee21a1e00ac4a4da848eed4253e9cf7

**Comment by fire1** [comment]
In general there must be -12v power supply  over pin 20 (or some other pin) ( this is for  newer type) 

Can you give me you datasheet of display...

**Comment by sinanhalici** [comment]
![htb1udgmrpxxxxcuxvxxq6xxfxxxx](https://user-images.githubusercontent.com/33650840/34342327-ecd77b98-e9bd-11e7-8b86-70f1a242994c.jpg)
I can't do contrast, so that there is nothing on the LCD.
please, help me...

**Comment by sinanhalici** [comment]
![25498321_1595493650499021_1583701695781226875_n](https://user-images.githubusercontent.com/33650840/34342336-363ec098-e9be-11e7-86fb-4c4bca88c5f1.jpg)
It's back of my LCD.

**Comment by fire1** [comment]
Something is wrong with display..  on scheme pin 20 is voltage OUT... Must be -12v
Disconnect all pins and make test only with power supply pins
You need negative voltage over pin 20

**Comment by sinanhalici** [comment]
Can you send me a picture or catalog of your LCD?
Maybe, I must give voltage from CN2 or CN3 from back of LCD.

**Comment by sinanhalici** [comment]
There is -0,45 Volt on the 20. pin

**Comment by fire1** [comment]
Hmmm this is something... Don't use other pads. Check for shorts

This is my display
https://www.buydisplay.com/download/manual/ERM24064-1_Series_Datasheet.pdf

**Comment by sinanhalici** [comment]
Yours is 24064-1 series, mine is 24064-2 series. There is something differenf between yours and mine.
I think there must be a solition, but how?

**Comment by fire1** [comment]
Ask supplier

**Comment by fire1** [comment]
This display had an unsupported controller

**Comment by LuisGP03** [comment]
Hi.

Are all resistors, capacitors, and diodes listed listed soldered to the MID_PCB_V1.6.2 board, or are there components that are discarded?

Which capacitors are ceramic and which are electrolytic?
[PCB_ gerber.zip](https://github.com/fire1/ArduinoMid/files/4555468/PCB_.gerber.zip)
