### ISSUE TITLE
pcb ratlines

### ISSUE THREAD

**Issue by sinanhalici** [fire1/ArduinoMid#6]
Will the hidden lines(ratlines) come on the pcb when I making&printing the pcb or do I use jump wires?

**Comment by fire1** [comment]
No. Use jumper wires. 
Also one important note 
Do Not place patch diode ( or check in printable version).

**Comment by sinanhalici** [comment]
![ratlines](https://user-images.githubusercontent.com/33650840/33598443-d881eca6-d9b3-11e7-97d3-2a1cc80e8bb0.PNG)

i mean that

**Comment by fire1** [comment]
Thous lines shows missing connection from 5v and GND lines, but they exist in real world. 
(Like an example double sided row:   +5V on upper right side / GND on bottom right side of PCB)

Keep in mind this version still does not have my approve as working correctly

**Comment by sinanhalici** [comment]
Ok, thanks a lot
Have a nice day

**Comment by magaiverzinho** [comment]
Hi , i can see you PCB project ?! Congratulations , nice job !
