### ISSUE TITLE
ratlines

### ISSUE THREAD

**Issue by sinanhalici** [fire1/ArduinoMid#7]
![ratlines](https://user-images.githubusercontent.com/33650840/34157294-10b835ac-e4d2-11e7-9ed1-27a246637526.PNG)

I asked you before about this issue, but i didn't understand.
Should i connect cables as we see on the Picture?

**Comment by fire1** [comment]
No!
Like i said earlier ... they  exist, Arduino Mega 2560 have several ground  & +5V  outputs.
Only R27,R28 (zero ohms resistors) can be wires
